### PR TITLE
updated the file_loader according to name changes in HDF

### PR DESCRIPTION
**Pull request by sichendart**

### CODE REVIEW

**Comment by decarlof** [comment]
To address  [this question](https://github.com/tomography/xfluo/issues/23) perhaps we should look at moving direct dependency to specific file formats from [file_loader.py](https://github.com/tomography/xfluo/blob/master/xfluo/widgets/file_loader.py)  to the [reader.py](https://github.com/tomography/xfluo/blob/master/xfluo/file_io/reader.py)

**Comment by decarlof** [comment]
May you please share [here](https://anl.app.box.com/folder/74709744988) an HDF data set using the new (image->data) name definition, so we can run a test?

**Comment by sichendart** [comment]
I just uploaded the test data to the box folder: XRFtomo Test Data/2-ID-E-new-HDF/Luxi_avg_201905, where "image" has been changed to "data".

**Comment by decarlof** [comment]
thanks! please let me know if your fork can load it so we can merge this pull request

**Comment by sichendart** [comment]
Yes, I tried it. Thanks.

**Comment by decarlof** [comment]
Great!

**Pull request merged**
